const express = require('express')
const authenticationRoute = require('./src/api/admin/authentication.route')
const patientRoute = require('./src/api/patient/patient.route')
const doctorRoute = require('./src/api/doctor/doctor.route')
const hospitalRoute = require('./src/api/hospital/hospital.route')
const pharmacyRoute = require('./src/api/pharmacy/pharmacy.route')
const specialityRoute = require('./src/api/speciality/speciality.route')
const tagsRoute = require('./src/api/tags/tags.route')
const languageRoute = require('./src/api/language/language.route')
const appointmentRoute = require('./src/api/appointment/appointment.route')
const healthtipsRoute = require('./src/api/healthtips/healthtips.route')
const labRoute = require('./src/api/lab/lab.route')
const labReportRoute = require('./src/api/labreports/labreport.route')
const feedbackRoute = require('./src/api/feedback/feedback.route')
const countryRoute = require('./src/api/country/country.route')
const regionRoute = require('./src/api/Region/region.route')
const commonRoute = require('./src/api/common/common.route')
const reportNameRoute = require('./src/api/reportName/reportName.route')
const medicineRoute = require('./src/api/medicine/medicine.route')
const hospitalStaffRoute = require('./src/api/hospitalStaff/hospitalStaff.route')
const userMessageRoute = require('./src/api/userMessage/userMessage.route')
const videoCallRoute = require('./src/api/videoCall/videoCall.route')
const app = express()
const cors = require('cors')

app.use(cors())
app.use(express.json())

app.use('/api', authenticationRoute)
app.use('/api', patientRoute)
app.use('/api', doctorRoute)
app.use('/api', hospitalRoute)
app.use('/api', pharmacyRoute)
app.use('/api', specialityRoute)
app.use('/api', tagsRoute)
app.use('/api', languageRoute)
app.use('/api', appointmentRoute)
app.use('/api', healthtipsRoute)
app.use('/api', labRoute)
app.use('/api', labReportRoute)
app.use('/api', feedbackRoute)
app.use('/api', countryRoute)
app.use('/api', regionRoute)
app.use('/api', commonRoute)
app.use('/api', reportNameRoute)
app.use('/api', medicineRoute)
app.use('/api', hospitalStaffRoute)
app.use('/api', hospitalStaffRoute)
app.use('/api', userMessageRoute)
app.use('/api', videoCallRoute)

app.use((req, res, next) => {
  res.status(404).json({
    error: 'URL request not found',
  })
})

module.exports = app
